In [1]:
from random import choice
from numpy import array,dot,random
import numpy as np

In [2]:
w=random.rand(2)
w

array([0.33361874, 0.73970282])

In [3]:
#Mcculloch-Pitts Model for AND gate
w=random.rand(2)
#w[0]=1
#w[1]=1
print(w)
train_data=[(array([0,0]),0),(array([0,1]),0),(array([1,0]),0),(array([1,1]),1)]
train_data

[0.6003839 0.6768463]


[(array([0, 0]), 0),
 (array([0, 1]), 0),
 (array([1, 0]), 0),
 (array([1, 1]), 1)]

In [4]:
w

array([0.6003839, 0.6768463])

In [5]:
def my_act(net):
  if net<1.5:
    return(0)
  else:
    return(1)

In [6]:
my_act(2)

1

In [7]:
#Threshold based activation (Hard Limit Activation Function)
act_function= lambda net: 0 if net<0.72 else 1

In [8]:
for x,_ in train_data:
  net=dot(x,w) #net value
  print("{} : {} -> {}".format(x[:2],net,act_function(net)))

[0 0] : 0.0 -> 0
[0 1] : 0.6768462991369215 -> 0
[1 0] : 0.6003839037394691 -> 0
[1 1] : 1.2772302028763907 -> 1


In [9]:
#Mcculloch-Pitts Model for OR gate
w=random.rand(2)
#w[0]=1
#w[1]=1
print(w)
train_data=[(array([0,0]),0),(array([0,1]),1),(array([1,0]),1),(array([1,1]),1)]
train_data

[0.20714806 0.556295  ]


[(array([0, 0]), 0),
 (array([0, 1]), 1),
 (array([1, 0]), 1),
 (array([1, 1]), 1)]

In [10]:
w

array([0.20714806, 0.556295  ])

In [11]:
act_function= lambda net: 0 if net<0.02 else 1

In [12]:
for x,_ in train_data:
  result=dot(x,w)
  print("{} : {} -> {}".format(x[:2],result,act_function(result)))

[0 0] : 0.0 -> 0
[0 1] : 0.5562949990269577 -> 1
[1 0] : 0.20714805869786912 -> 1
[1 1] : 0.7634430577248268 -> 1


Rosenblat's Neuron : Instead of using fixed weight with no learning scope, he introduced random weights and bias with learning scope

In [13]:
#assign a random threshold value
act_function= lambda x: 0 if x<1.5 else 1
train_data=[(array([0,0,1]),0),(array([0,1,1]),1),(array([1,0,1]),1),(array([1,1,1]),1)]
#random.seed(10)
w=random.rand(3)
errors=[]
eta=0.1

In [14]:
print(w)

[0.43462402 0.62510444 0.37563546]


In [15]:
train_data

[(array([0, 0, 1]), 0),
 (array([0, 1, 1]), 1),
 (array([1, 0, 1]), 1),
 (array([1, 1, 1]), 1)]

In [16]:
x,expected=choice(train_data)
print(x,expected)

[1 1 1] 1


In [17]:
dot(w,x)

1.4353639275936159

In [18]:
n=1000
#Training
for i in range(n):
  x,expected=choice(train_data)
  net=dot(w,x)
  y_pred=act_function(net)
  error=expected-y_pred
  errors.append(error)
  w+=eta*error*x

In [19]:
w

array([0.73462402, 0.82510444, 0.87563546])

In [20]:
#Testing
for x,_ in train_data:
  net=dot(x,w)
  print("{} : {} -> {}".format(x[:3],net,act_function(net)))

[0 0 1] : 0.8756354642358479 -> 0
[0 1 1] : 1.7007399048738772 -> 1
[1 0 1] : 1.6102594869555866 -> 1
[1 1 1] : 2.435363927593616 -> 1


In [21]:
w

array([0.73462402, 0.82510444, 0.87563546])